[package]
name = "tracer"
version = "0.1.0"
authors = ["Benn Sundsrud <benn.sundsrud@gmail.com>"]

[dependencies]
tower-service = "*"
futures = "^0.1"
tokio-io = "*"
tokio-reactor = "*"
tokio-timer = "*"
tokio-tcp = "*"
log = "*"
failure = "*"
http = "*"
futures-cpupool = "^0.1"