[package]
name = "tracer-metrics"
version = "0.1.0"
authors = ["Benn Sundsrud <benn.sundsrud@gmail.com>"]
edition = "2018"

[dependencies]
crossbeam = "0.7.3"
fnv = "1.0.6"
hdrhistogram = { version = "7.0.0", default-features = false }
